name: learn-github-actions
on: [push]
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          bash addenvtobashrc.sh
          ls
      - run: env | sort
        shell: bash -l {0}
        name: withbashl
