name: learn-github-actions
on: [push]
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo github.repository is ${{ github.repository }}
      - uses: actions/checkout@v2
        with: 
          repository: banshee/githubactionsdemo
          path: other
      - run: |
         ls
         echo =====
         env
