name: learn-github-actions
on: [push]
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo github.repository is ${{ github.repository }}
      - run: |
         echo github secret is '${{ secrets.GITHUB_TOKEN }}'
         echo =====
         env
      - run: |
          date > updatedFile.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add updatedFile.txt
          git commit -m "new date" .
          git push
