name: learn-github-actions
on: [push]
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: export FOO=bar
      - run: echo should be foo $FOO stuff
      - run: uname -a
      - run: cat /proc/cpuinfo
      - run: pwd
      - run: find .
      - run: env | sort
